name: sage-binder-env

channels:
  - conda-forge
  - defaults

dependencies:
  - jupyterlab
  # Required by the SageMath kernel in Jupyter
  - ipywidgets
  # Install the full distribution of SageMath. The resulting image might take a
  # long time to load on binder. Replace sage with sagelib, to use a minimal
  # distribution of SageMath, without plotting, without symbolic computations, ….
   - sage=9.6
   - gap
